config/routes.rb
Rails.application.routes.draw do
  root to: 'microposts#index'
  resources :microposts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  validates :content,presence: true
  validates :content,length: { in: 1..140}
  validates :name,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show,:edit,:update,:destroy]

  def index
    @microposts = Micropost.all
  end

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = Micropost.new(micropost_params)
    if params[:back]
      render :new
    else
      if @micropost.save
        redirect_to microposts_path,notice: "メッセージを作成しました!"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @micropost.update(micropost_params)
      redirect_to microposts_path,notice: "メッセージを更新しました!"
    end
  end

  def destroy
    @micropost.destroy
    redirect_to microposts_path, notice: "メッセージを削除しました!"
  end

  def confirm
    @micropost = Micropost.new(micropost_params)
    render :new if @micropost.invalid?
  end

  private

  def micropost_params
    params.require(:micropost).permit(:name,:content)
  end

  def set_micropost
    @micropost = Micropost.find(params[:id])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_microposts_path
    elsif action_name == 'edit'
      micropost_path
    end
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><a href="#">Micropost</a></li>
        <li><a href="#"></a></li>
      </ul>
    </header>
    <%= yield %>
      <footer>
        <p>利用規約　プライバシーポリシー　Cookie 広告情報 © 2020 Micropost,Inc.</p>
      </footer>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: @micropost,local: true, url: choose_new_or_edit) do |form| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= @micropost.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @micropost.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
    <% end %>
    <div class='micropost_content'>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class='micropost_content'>
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <%= form.submit %>
    <% end %>
    <%= link_to "投稿一覧画面に戻る",microposts_path %>

app/views/microposts/confirm.html.erb
<h3>以下の内容で、送信する</h3>
<%= form_with(model: @micropost,url: microposts_path, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :content %>
  <p>投稿者:<%= @micropost.name %></p>
  <p>本文:<%= @micropost.content %></p>
  <%= form.submit "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/microposts/edit.html.erb
<h2>メッセージを編集する</h2>
<%= render 'form' %>

app/views/microposts/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand href="#"></a>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="">ログイン</a></li>
        <li><a href="">アカウントを作成</a></li>
        <div class="col-lg-6">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="キーワードを検索...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <img class="logo"src="/assets/img_logo_pc.jpg" alt="">
  <div class='wrapper clearfix'>
    <aside class="side_menu">
          <div class="box1">
          <h3><span class="glyphicon glyphicon-apple" aria-hidden="true" style="font-size: 50px" style="color: red"></span>Micropost JAPAN   <span class="label label-info">フォローする</span></h3>
          <p class='miki'>@MicropostJP</p>
          <p>日本語版Micropost公式アカウントです。<br>
            サービスに関してのご質問、お問い合わせは,<br>
             https://support.micropost.com および<br>
              https://support.micropost.com/articles/486421をご利用ください。</p>
           <span class="glyphicon glyphicon-map-marker" aria-hidden="true">東京都中央区</span>
           <span class="glyphicon glyphicon-link" aria-hidden="true">blog.micropost.com/ja_jp.html</span>
           <span class="glyphicon glyphicon-heart" aria-hidden="true">誕生日: 3月21日</span><br>
           <span class="glyphicon glyphicon-list-alt" aria-hidden="true">2007年6月からMicropostを利用しています</span>
           <p>141フォロー中　100万フォロワー</p>
           </div>
          <h2>Micropost</h2>
              <table class='table'>
                <tr>
                  <th>投稿者</th>
                  <th>投稿内容</th>
                </tr>
                <% @microposts.each do |micropost| %>
                  <tr>
                    <td><%= micropost.name %></td>
                    <td><%= micropost.content %></td>
                    <td><%= link_to '詳細を確認する',micropost_path(micropost.id) %></td>
                    <td><%= link_to 'メッセージを編集する',edit_micropost_path(micropost.id) %></td>
                    <td><%= link_to 'メッセージを削除する', micropost_path(micropost.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
                  </tr>
                  <% end %>
                </table>
                <%= link_to '新しいMicropostを作成する',new_micropost_path %>
        </aside>
        <article class='contents'>
            <div class="box5">
              <h3>Micropostを使ってみよう!</h3>
              <p>今すぐ登録して、タイムラインをカスタマイズしましょう!</p>
              <span class="label label-info">アカウント作成</span>
            </div>
            <div class="box3">
              <h2>おすすめメッセージ</h2>
            </div>
            <div class='box4'>
              <h4><span class="glyphicon glyphicon-star-empty" aria-hidden="true">Micropost DEV JAPAN　　<span class="label label-info">フォローする</span></h4>
            </div>
            <div class='box4'>
            <h4><span class="glyphicon glyphicon-heart" aria-hidden="true">Micropostメディア　　<span class="label label-info">フォローする</span></h4>
          </div>
          <div class='box4'>
            <h4><span class="glyphicon glyphicon-bell" aria-hidden="true">Micropost Safety　<span class="label label-info">フォローする</span></h4>
      </div>
    </article>
  </div>

app/views/microposts/new.html.erb
<h2>メッセージを作成する</h2>
<%= render 'form' %>

app/views/microposts/show.html.erb
<h1>メッセージ詳細画面</h1>
<p>内容:<%= @micropost.content %></p>